---
- name: "Install Pre-Requisites java-1.8.0-openjdk-devel"
  package:
    name: "{{ jenkins.pre1 }}"
    state: present
- name: "Ensure Jenkins Repository is Installed"
  yum_repository:
    name: jenkins
    state: present
    description: Official Jenkins Yum Repo
    baseurl: http://pkg.jenkins.io/redhat
    gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    gpgcheck: yes
    enabled: yes    
- name: "Install Jenkins"
  package:
    name: "{{ jenkins.package }}"
    update_cache: yes
    state: present
- name: "Enable and Start the Jenkins Service"
  service:
    name: jenkins
    enabled: yes
    state: started
- name: "Enable and Start Firewalld"
  service:
    name: firewalld
    enabled: yes
    state: started
- name: "Open Firewall Port"
  firewalld:
    zone: public
    port: 8080/tcp
    permanent: true
    immediate: true
    state: enabled
- name: Ansible copy directory to the remote server
  copy:
    src: /var/lib/jenkins/secrets/initialAdminPassword
    dest: /share
    remote_src: yes
